import { useState } from 'react';
import { Ms, StatusBadge, STATUS_CFG, TemplateStatus, fmtDate } from './shared';
import SectionCard from './SectionCard';
import QuestionModal from './QuestionModal';
import {
  updateTemplateSections,
  updateTemplateStatus as updateTemplateStatusLocal,
  createNewVersion,
} from '@/actions/templateActions';
import {
  createTemplate,
  updateTemplateStatus,
} from '@/services/templateService';

function uid() {
  return crypto.randomUUID();
}

const STATUS_TRANSITIONS: Record<TemplateStatus, TemplateStatus[]> = {
  IN_DESIGN: ['IN_REVISION'],
  IN_REVISION: ['IN_DESIGN', 'APPROVED'],
  APPROVED: [],
};

const STATUS_LABELS: Record<string, string> = {
  IN_REVISION: 'Send to Revision',
  IN_DESIGN: 'Back to Design',
  APPROVED: 'Approve',
};

export default function TemplateBuilder({
  template,
  onUpdated,
  onNewVersion,
}: {
  template: any;
  onUpdated: (t: any) => void;
  onNewVersion: (t: any) => void;
}) {
  const [sections, setSections] = useState<any[]>(template.sections);
  const [saving, setSaving] = useState(false);
  const [editQ, setEditQ] = useState<{
    question: any | null;
    sectionId: string;
  } | null>(null);
  const [dirty, setDirty] = useState(false);
  const [newVerLoading, setNewVerLoading] = useState(false);
  const [changingStatus, setChangingStatus] = useState(false);
  const [newStatus, setNewStatus] = useState('');
  const [statusSaving, setStatusSaving] = useState(false);

  const readOnly = template.status === 'APPROVED';

  // Keep sections in sync when template changes
  const [lastId, setLastId] = useState(template.id);
  if (template.id !== lastId) {
    setSections(template.sections);
    setLastId(template.id);
    setDirty(false);
  }

  const updateSection = (updated: any) => {
    setSections((s) => s.map((sec) => (sec.id === updated.id ? updated : sec)));
    setDirty(true);
  };

  const deleteSection = (id: string) => {
    setSections((s) => s.filter((sec) => sec.id !== id));
    setDirty(true);
  };

  const addSection = () => {
    const newSec = {
      id: uid(),
      name: 'New Section',
      order: sections.length + 1,
      questions: [],
    };
    setSections((s) => [...s, newSec]);
    setDirty(true);
  };

  const saveSection = async () => {
    setSaving(true);
    try {
      const updated = await updateTemplateSections(template.id, sections);
      onUpdated(updated);
      setDirty(false);
    } finally {
      setSaving(false);
    }
  };

  const changeStatus = async (status: TemplateStatus) => {
    setSaving(true);
    try {
      // Always save sections first
      await updateTemplateSections(template.id, sections);
      setDirty(false);

      // On first send (IN_DESIGN → IN_REVISION), push to backend API
      if (template.status === 'IN_DESIGN' && status === 'IN_REVISION') {
        const backendTemplate = await createTemplate({
          ...template,
          sections,
          status,
        });
        // Re-load from backend to get proper UUIDs for questions/options
        const { getTemplateById } = await import('@/services/templateService');
        const synced = await getTemplateById(backendTemplate.id).catch(
          () => backendTemplate,
        );
        await updateTemplateStatusLocal(template.id, status);
        onUpdated({ ...synced, status });
        return;
      }

      const updated = await updateTemplateStatus(template.id, status);
      onUpdated(updated);
    } finally {
      setSaving(false);
    }
  };

  const handleNewVersion = async () => {
    setNewVerLoading(true);
    try {
      const newT = await createNewVersion(template.groupId);
      onNewVersion(newT);
    } finally {
      setNewVerLoading(false);
    }
  };

  // Question modal save — payload is { question, followUps[] }
  const handleSaveQuestion = ({
    question: q,
    followUps,
  }: {
    question: any;
    followUps: any[];
  }) => {
    if (!editQ) return;
    setSections((secs) =>
      secs.map((sec) => {
        if (sec.id !== editQ.sectionId) return sec;
        const exists = sec.questions.find((x: any) => x.id === q.id);
        let questions: any[];
        if (exists) {
          // Remove old follow-ups that were previously generated by this question
          const oldFollowUpIds = new Set(
            (exists.options ?? [])
              .map((o: any) => o.followUpQuestionId)
              .filter(Boolean),
          );
          const withoutOld = sec.questions.filter(
            (x: any) => !oldFollowUpIds.has(x.id),
          );
          const mainIdx = withoutOld.findIndex((x: any) => x.id === q.id);
          const updated = withoutOld.map((x: any) =>
            x.id === q.id ? { ...q, order: x.order } : x,
          );
          updated.splice(mainIdx + 1, 0, ...followUps);
          questions = updated.map((x: any, i: number) => ({
            ...x,
            order: i + 1,
          }));
        } else {
          const base = sec.questions.length;
          const newFollowUps = followUps.map((f, i) => ({
            ...f,
            order: base + 2 + i,
          }));
          questions = [
            ...sec.questions,
            { ...q, order: base + 1 },
            ...newFollowUps,
          ];
        }
        return { ...sec, questions };
      }),
    );
    setDirty(true);
    setEditQ(null);
  };

  const transitions =
    STATUS_TRANSITIONS[template.status as TemplateStatus] ?? [];

  return (
    <>
      <div
        style={{
          flex: 1,
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden',
        }}
      >
        {/* Header */}
        <div
          style={{
            padding: '20px 28px 16px',
            borderBottom: '1px solid #f1f5f9',
            background: '#fff',
            position: 'sticky',
            top: 0,
            zIndex: 10,
          }}
        >
          <div
            style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'flex-start',
              flexWrap: 'wrap',
              gap: 12,
            }}
          >
            <div>
              <div
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 8,
                  marginBottom: 4,
                }}
              >
                <h2
                  style={{
                    fontSize: 18,
                    fontWeight: 700,
                    color: '#0f172a',
                    margin: 0,
                  }}
                >
                  {template.name}
                </h2>
                <span
                  style={{
                    fontSize: 12,
                    color: '#94a3b8',
                    background: '#f1f5f9',
                    borderRadius: 6,
                    padding: '2px 8px',
                    fontWeight: 500,
                  }}
                >
                  v{template.version}
                </span>
                <StatusBadge status={template.status} />
              </div>
              <p style={{ fontSize: 11, color: '#94a3b8', margin: 0 }}>
                Created {fmtDate(template.createdAt)} · {sections.length}{' '}
                section{sections.length !== 1 ? 's' : ''} ·{' '}
                {sections.reduce(
                  (a: number, s: any) => a + s.questions.length,
                  0,
                )}{' '}
                questions
              </p>
            </div>

            <div
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                flexWrap: 'wrap',
              }}
            >
              {/* Status transitions */}
              {transitions.map((s) => (
                <button
                  key={s}
                  onClick={() => changeStatus(s)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 5,
                    borderRadius: 8,
                    border: `1px solid ${STATUS_CFG[s].border}`,
                    background: STATUS_CFG[s].bg,
                    color: STATUS_CFG[s].color,
                    padding: '7px 14px',
                    fontSize: 12,
                    fontWeight: 600,
                    cursor: 'pointer',
                  }}
                >
                  <Ms
                    icon={STATUS_CFG[s].icon}
                    style={{ fontSize: 15, color: STATUS_CFG[s].color }}
                  />
                  {STATUS_LABELS[s]}
                </button>
              ))}

              {/* Change Status */}
              <button
                onClick={() => {
                  setNewStatus(
                    template.status === 'APPROVED'
                      ? 'DRAFT'
                      : template.status === 'DRAFT'
                        ? 'APPROVED'
                        : 'DRAFT',
                  );
                  setChangingStatus(true);
                }}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: 5,
                  borderRadius: 8,
                  border: '1px solid #e2e8f0',
                  background: '#fff',
                  color: '#374151',
                  padding: '7px 14px',
                  fontSize: 12,
                  fontWeight: 600,
                  cursor: 'pointer',
                }}
              >
                <Ms icon="swap_horiz" style={{ fontSize: 15 }} />
                Change Status
              </button>

              {/* New version — only from APPROVED */}
              {template.status === 'APPROVED' && (
                <button
                  onClick={handleNewVersion}
                  disabled={newVerLoading}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 5,
                    borderRadius: 8,
                    border: '1px solid #e2e8f0',
                    background: '#fff',
                    color: '#374151',
                    padding: '7px 14px',
                    fontSize: 12,
                    fontWeight: 600,
                    cursor: 'pointer',
                  }}
                >
                  <Ms icon="add_circle_outline" style={{ fontSize: 15 }} />
                  {newVerLoading
                    ? 'Creating…'
                    : `New version (v${(parseFloat(template.version) + 1).toFixed(1)})`}
                </button>
              )}

              {/* Save */}
              {!readOnly && (
                <button
                  onClick={saveSection}
                  disabled={!dirty || saving}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 5,
                    borderRadius: 8,
                    border: 'none',
                    background: dirty ? '#0f172a' : '#e2e8f0',
                    color: dirty ? '#fff' : '#94a3b8',
                    padding: '7px 14px',
                    fontSize: 12,
                    fontWeight: 600,
                    cursor: dirty ? 'pointer' : 'default',
                  }}
                >
                  <Ms
                    icon="save"
                    style={{ fontSize: 15, color: dirty ? '#fff' : '#94a3b8' }}
                  />
                  {saving ? 'Saving…' : 'Save'}
                </button>
              )}
            </div>
          </div>

          {readOnly && (
            <div
              style={{
                marginTop: 12,
                display: 'flex',
                alignItems: 'center',
                gap: 8,
                padding: '8px 14px',
                borderRadius: 8,
                background: '#f0fdf4',
                border: '1px solid #bbf7d0',
              }}
            >
              <Ms icon="lock" style={{ fontSize: 15, color: '#15803d' }} />
              <p
                style={{
                  fontSize: 12,
                  color: '#15803d',
                  margin: 0,
                  fontWeight: 500,
                }}
              >
                This template is approved and locked. Create a new version to
                make changes.
              </p>
            </div>
          )}
        </div>

        {/* Sections */}
        <div
          style={{
            flex: 1,
            overflowY: 'auto',
            padding: '24px 28px',
            display: 'flex',
            flexDirection: 'column',
            gap: 16,
            maxWidth: 840,
          }}
        >
          {sections.length === 0 && (
            <div style={{ textAlign: 'center', paddingTop: 60 }}>
              <Ms
                icon="view_agenda"
                style={{
                  fontSize: 48,
                  color: '#e2e8f0',
                  display: 'block',
                  margin: '0 auto 12px',
                }}
              />
              <p
                style={{
                  fontSize: 14,
                  fontWeight: 600,
                  color: '#64748b',
                  margin: '0 0 4px',
                }}
              >
                No sections yet
              </p>
              <p style={{ fontSize: 13, color: '#94a3b8', margin: 0 }}>
                Add a section to start building this template
              </p>
            </div>
          )}

          {sections.map((sec, i) => (
            <SectionCard
              key={sec.id}
              section={sec}
              index={i}
              readOnly={readOnly}
              onUpdate={updateSection}
              onDelete={() => deleteSection(sec.id)}
              onEditQuestion={(q, sectionId) =>
                setEditQ({ question: q, sectionId })
              }
            />
          ))}

          {!readOnly && (
            <button
              onClick={addSection}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: 8,
                padding: '14px',
                borderRadius: 12,
                border: '2px dashed #cbd5e1',
                background: 'none',
                color: '#64748b',
                fontSize: 13,
                fontWeight: 500,
                cursor: 'pointer',
              }}
            >
              <Ms icon="add" style={{ fontSize: 18 }} />
              Add section
            </button>
          )}
        </div>
      </div>

      {editQ && (
        <QuestionModal
          question={editQ.question}
          onSave={handleSaveQuestion}
          onClose={() => setEditQ(null)}
        />
      )}

      {changingStatus && (
        <div
          style={{
            position: 'fixed',
            inset: 0,
            background: 'rgba(0,0,0,0.4)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 50,
          }}
        >
          <div
            style={{
              background: '#fff',
              borderRadius: 14,
              padding: 28,
              width: 380,
              boxShadow: '0 20px 60px rgba(0,0,0,0.15)',
            }}
          >
            <h2 style={{ fontSize: 16, fontWeight: 700, margin: '0 0 4px' }}>
              Change Status
            </h2>
            <p style={{ fontSize: 12, color: '#64748b', margin: '0 0 20px' }}>
              {template.name} · v{template.version}
            </p>
            <select
              value={newStatus}
              onChange={(e) => setNewStatus(e.target.value)}
              style={{
                width: '100%',
                borderRadius: 8,
                border: '1px solid #e2e8f0',
                padding: '8px 10px',
                fontSize: 13,
                outline: 'none',
                fontFamily: 'inherit',
                marginBottom: 16,
              }}
            >
              {['DRAFT', 'APPROVED', 'ARCHIVED'].map((s) => (
                <option key={s} value={s}>
                  {s}
                </option>
              ))}
            </select>
            <div
              style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}
            >
              <button
                onClick={() => setChangingStatus(false)}
                style={{
                  borderRadius: 8,
                  border: '1px solid #e2e8f0',
                  background: '#fff',
                  padding: '8px 16px',
                  fontSize: 13,
                  cursor: 'pointer',
                  color: '#374151',
                }}
              >
                Cancel
              </button>
              <button
                disabled={statusSaving}
                onClick={async () => {
                  setStatusSaving(true);
                  try {
                    const updated = await updateTemplateStatus(
                      template.id,
                      newStatus,
                    );
                    onUpdated(updated);
                    setChangingStatus(false);
                  } finally {
                    setStatusSaving(false);
                  }
                }}
                style={{
                  borderRadius: 8,
                  border: 'none',
                  background: '#0f172a',
                  color: '#fff',
                  padding: '8px 16px',
                  fontSize: 13,
                  fontWeight: 600,
                  cursor: 'pointer',
                }}
              >
                {statusSaving ? 'Saving…' : 'Update Status'}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
